"""Train route_freight_model.py across the full synthetic route grid.

WHY THIS EXISTS AS A SEPARATE SCRIPT
-------------------------------------
route_freight_model.py's train() trains one RandomForestRegressor per
(lane, horizon) — with the full grid generated by
generate_synthetic_route_grid.py that's 335 lanes x 3 horizons = 1,005
models. Training all of them in a single train() call can exceed available
memory/time on a small machine (this project was developed against a
single-core, ~4GB sandbox). This script trains the grid in batches,
checkpointing each batch's artifacts to disk, then merges the batches into
the same models/route_freight_model_h{1,2,3}.joblib and
models/route_freight_model_metadata.json files a single train() call would
have produced. The merged result is behaviourally identical to one full
run — this is purely a memory/time workaround, not a different training
procedure.

USAGE
-----
    cd ml-service
    python scripts/generate_synthetic_route_grid.py   # only if the CSV changed
    python scripts/train_route_freight_grid.py

Re-run any time data/synthetic/route_freight_observations.csv (or
data/production/route_freight_observations.csv, once it has enough rows)
changes.
"""
from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

import joblib
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from route_freight_model import export_lane_files, _key, train, _hash_file, SCHEMA_VERSION, MIN_OBSERVATIONS, NUMERIC, CATEGORICAL  # noqa: E402

OBS_FILE = ROOT / "data" / "synthetic" / "route_freight_observations.csv"
MODELS_DIR = ROOT / "models"
BATCH_SIZE = 85  # ~85 lanes x 3 horizons fits comfortably in a few minutes on one core


def _lane_keys(df: pd.DataFrame) -> list[str]:
    return sorted(df.apply(lambda r: _key(r.origin, r.destination, r.route_id), axis=1).unique())


def _train_batch(df: pd.DataFrame, batch_keys: set[str], out_dir: Path) -> dict:
    df = df.copy()
    df["_key"] = df.apply(lambda r: _key(r.origin, r.destination, r.route_id), axis=1)
    chunk = df[df["_key"].isin(batch_keys)].drop(columns=["_key"])

    tmp_data_dir = out_dir / "data"
    tmp_out_dir = out_dir / "out"
    tmp_data_dir.mkdir(parents=True, exist_ok=True)
    tmp_out_dir.mkdir(parents=True, exist_ok=True)
    chunk.to_csv(tmp_data_dir / "route_freight_observations.csv", index=False)

    return train(output_dir=tmp_out_dir, data_dir=tmp_data_dir, allow_synthetic=True)


def main():
    df = pd.read_csv(OBS_FILE)
    keys = _lane_keys(df)
    batches = [keys[i:i + BATCH_SIZE] for i in range(0, len(keys), BATCH_SIZE)]
    print(f"{len(keys)} lanes -> {len(batches)} batches of up to {BATCH_SIZE}")

    merged_bundles: dict[int, dict] = {1: {}, 2: {}, 3: {}}
    merged_metrics: dict = {}
    merged_skipped: dict = {}
    total_eligible = total_verified = total_synthetic = 0

    with tempfile.TemporaryDirectory(prefix="route_freight_train_") as tmp:
        tmp = Path(tmp)
        for i, batch_keys in enumerate(batches):
            print(f"--- batch {i + 1}/{len(batches)} ({len(batch_keys)} lanes) ---")
            out_dir = tmp / f"batch_{i}"
            meta = _train_batch(df, set(batch_keys), out_dir)
            total_eligible += meta.get("eligible_rows", 0)
            total_verified += meta.get("verified_rows", 0)
            total_synthetic += meta.get("synthetic_rows", 0)
            merged_metrics.update(meta.get("metrics", {}))
            merged_skipped.update(meta.get("skipped_routes", {}))
            for h in (1, 2, 3):
                p = out_dir / "out" / f"route_freight_model_h{h}.joblib"
                if p.exists():
                    merged_bundles[h].update(joblib.load(p))

        for h in (1, 2, 3):
            if merged_bundles[h]:
                joblib.dump(merged_bundles[h], MODELS_DIR / f"route_freight_model_h{h}.joblib", compress=3)

        total = sum(len(hm) for hm in merged_metrics.values())
        failing = [
            (key, h) for key, hm in merged_metrics.items() for h in hm if not hm[h]["model_beats_baseline"]
        ]
        final_meta = {
            "status": "active" if any(merged_bundles.values()) else "inactive",
            "schema_version": SCHEMA_VERSION,
            "target": "synthetic_route_freight_usd_per_t",
            "data_mode": "synthetic_mvp",
            "source_file": str(OBS_FILE),
            "dataset_sha256": _hash_file(OBS_FILE),
            "eligible_rows": total_eligible,
            "verified_rows": total_verified,
            "synthetic_rows": total_synthetic,
            "routes_with_models": sorted(set(k for hb in merged_bundles.values() for k in hb)),
            "metrics": merged_metrics,
            "skipped_routes": merged_skipped,
            "minimum_observations_per_route": MIN_OBSERVATIONS,
            "features": NUMERIC + CATEGORICAL,
            "interval_note": (
                "Prediction bounds, when exposed, are ensemble-tree percentiles "
                "and are not statistical confidence intervals."
            ),
            "baseline_summary": {
                "total_route_horizon_models": total,
                "passed": total - len(failing),
                "failed": len(failing),
                "failed_route_horizons": [f"{key} H+{h}" for key, h in failing],
            },
            "training_note": (
                "Trained in batches by this script to fit a single-core, "
                "memory-constrained environment's time/RAM limits; the "
                "merged artifacts are equivalent to a single full "
                "route_freight_model.py:train() run over all lanes."
            ),
        }
        (MODELS_DIR / "route_freight_model_metadata.json").write_text(json.dumps(final_meta, indent=2))

    # Re-pack into per-lane files so the service can load models lazily
    # (needed to fit small hosts) and drop the RAM-hungry monolithic files.
    n_lanes = export_lane_files(MODELS_DIR, remove_monolithic=True)
    print(f"exported {n_lanes} lane files to {MODELS_DIR / 'lanes'}")

    print(f"routes_with_models: {len(final_meta['routes_with_models'])}")
    print(f"baseline_summary: {final_meta['baseline_summary']}")
    print(f"status: {final_meta['status']}")


if __name__ == "__main__":
    main()
